version: "2"
services:
   namenode:
      image: apache/hadoop:3.3.5
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870  # NameNode Web UI
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      networks:
        - hadoop_network
      volumes:
        - ./pagerank:/pagerank

   datanode:
      image: apache/hadoop:3.3.5
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
      ports:
        - 9864:9864  # DataNode Web UI
      networks:
        - hadoop_network

   resourcemanager:
      image: apache/hadoop:3.3.5
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
        - 8088:8088  # YARN Resource Manager UI
      env_file:
        - ./config
      environment:
         YARN-SITE.XML_yarn.log-aggregation-enable: "true"
         YARN-SITE.XML_yarn.log-aggregation.retain-seconds: "86400"
      networks:
        - hadoop_network

   nodemanager:
      image: apache/hadoop:3.3.5
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
      networks:
        - hadoop_network

networks:
  hadoop_network:
    driver: bridge